{application,exrm,
             [{registered,[]},
              {description,"Exrm, or Elixir Release Manager, provides mix tasks for building,\nupgrading, and controlling release packages for your application.\n"},
              {applications,[kernel,stdlib,elixir,logger,relx]},
              {vsn,"1.0.2"},
              {modules,['Elixir.Mix.Tasks.Release',
                        'Elixir.Mix.Tasks.Release.Clean',
                        'Elixir.Mix.Tasks.Release.Plugins',
                        'Elixir.ReleaseManager.Appups',
                        'Elixir.ReleaseManager.Config',
                        'Elixir.ReleaseManager.Deps',
                        'Elixir.ReleaseManager.Plugin',
                        'Elixir.ReleaseManager.Plugin.Appups',
                        'Elixir.ReleaseManager.Plugin.Consolidation',
                        'Elixir.ReleaseManager.Utils',
                        'Elixir.ReleaseManager.Utils.Logger']}]}.